# Generated by Django 4.2.26 on 2025-11-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("Urgent", "Urgent"),
                            ("Normal", "Normal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order_index", models.IntegerField()),
                (
                    "printing_type",
                    models.CharField(
                        blank=True,
                        choices=[("Offset", "Offset"), ("Digital", "Digital")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("is_vip", models.BooleanField(default=False)),
                ("deadline", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.BigIntegerField()),
                (
                    "client",
                    models.ForeignKey(
                        db_column="client_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="status",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="statuses.taskstatus",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["order_index"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("text", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.BigIntegerField()),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_comment_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="tasks.comment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        db_column="task_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "comments",
                "ordering": ["created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="attachments/%Y/%m/%d/")),
                ("size", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        db_column="task_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "attachments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("timestamp", models.BigIntegerField()),
                ("type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        db_column="task_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
                "ordering": ["-timestamp"],
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["client_id"], name="idx_task_client"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="idx_task_status"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["parent_id"], name="idx_task_parent"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["deadline"], name="idx_task_deadline"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["urgency"], name="idx_task_urgency"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["order_index"], name="idx_task_order"),
        ),
    ]
