# Generated by Django 4.2.26 on 2025-11-30 17:04

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=clients.models.generate_uuid,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("New", "New"), ("Existing", "Existing")],
                        max_length=20,
                    ),
                ),
                ("number", models.CharField(max_length=50, unique=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "clients",
                "ordering": ["name"],
                "managed": True,
            },
        ),
    ]
