# Generated by Django 4.2.26 on 2025-11-30 17:04

from django.db import migrations, models
import statuses.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=statuses.models.generate_uuid,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=50)),
                ("order_index", models.IntegerField()),
                ("is_finished", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("allowed_next_statuses", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "task_statuses",
                "ordering": ["order_index"],
                "managed": True,
            },
        ),
    ]
